// Weapon data: fireMode = auto | semi | bolt | burst. fireInterval = 60 / fireRateRPM (full auto). spreadRad: bullet spread scale.
(function () {
  const TheGame = (window.TheGame = window.TheGame || {});

  TheGame.WeaponConfig = {
    m4a1: {
      id: "m4a1",
      slot: "primary",
      name: "HK416",
      fireSoundId: "hk416",
      fireMode: "auto",
      magazineSize: 30,
      reserveAmmo: 180,
      damage: 26,
      range: 90,
      fireRateRPM: 750,
      fireInterval: 60 / 750,
      reloadTime: 1.9,
      switchTime: 0.45,
      recoilPitch: 0.0032,
      spreadRad: 0.0025,
      role: "stable CQB rifle",
      hitScore: 10,
      killScore: 100,
    },
    ak74: {
      id: "ak74",
      slot: "primary",
      name: "AK-74",
      fireSoundId: "ak74",
      fireMode: "auto",
      magazineSize: 30,
      reserveAmmo: 150,
      damage: 34,
      range: 85,
      fireRateRPM: 600,
      fireInterval: 60 / 600,
      reloadTime: 2.35,
      switchTime: 0.5,
      recoilPitch: 0.012,
      spreadRad: 0.0065,
      role: "high damage rifle",
      hitScore: 10,
      killScore: 100,
    },
    awm: {
      id: "awm",
      slot: "primary",
      name: "AWM",
      fireSoundId: "awm",
      fireMode: "bolt",
      magazineSize: 1,
      reserveAmmo: 30,
      damage: 200,
      range: 420,
      fireRateRPM: 45,
      fireInterval: 60 / 45,
      reloadTime: 1.2,
      switchTime: 0.55,
      recoilPitch: 0.03,
      spreadRad: 0.001,
      scopes: [2, 4],
      role: "precision high-damage weapon",
      hitScore: 10,
      killScore: 100,
    },
    mp7: {
      id: "mp7",
      slot: "primary",
      name: "MP7",
      fireSoundId: "mp7",
      fireMode: "auto",
      magazineSize: 40,
      reserveAmmo: 200,
      damage: 19,
      range: 28,
      fireRateRPM: 950,
      fireInterval: 60 / 950,
      reloadTime: 1.75,
      switchTime: 0.42,
      recoilPitch: 0.0042,
      spreadRad: 0.0078,
      role: "high fire-rate CQB SMG",
      hitScore: 10,
      killScore: 100,
    },
    beretta92f: {
      id: "beretta92f",
      slot: "secondary",
      name: "Beretta 92F",
      fireSoundId: "beretta92f",
      fireMode: "semi",
      magazineSize: 15,
      reserveAmmo: 75,
      damage: 28,
      range: 62,
      fireRateRPM: 420,
      fireInterval: 60 / 420,
      reloadTime: 1.35,
      switchTime: 0.32,
      recoilPitch: 0.004,
      spreadRad: 0.0025,
      role: "stable pistol",
      hitScore: 10,
      killScore: 100,
    },
    deagle: {
      id: "deagle",
      slot: "secondary",
      name: "Desert Eagle",
      fireSoundId: "deagle",
      fireMode: "semi",
      magazineSize: 7,
      reserveAmmo: 35,
      damage: 55,
      range: 68,
      fireRateRPM: 240,
      fireInterval: 60 / 240,
      reloadTime: 1.65,
      switchTime: 0.38,
      recoilPitch: 0.016,
      spreadRad: 0.004,
      role: "high damage pistol",
      hitScore: 10,
      killScore: 100,
    },
    glock18: {
      id: "glock18",
      slot: "secondary",
      name: "Glock 18",
      fireSoundId: "glock18",
      fireMode: "burst",
      burstCount: 3,
      burstInterval: 0.08,
      magazineSize: 21,
      reserveAmmo: 84,
      damage: 18,
      range: 58,
      fireRateRPM: 900,
      fireInterval: 0.22,
      reloadTime: 1.45,
      switchTime: 0.34,
      recoilPitch: 0.006,
      spreadRad: 0.0065,
      role: "close-range burst pistol",
      hitScore: 10,
      killScore: 100,
    },
  };
})();
